course/api/urls.py
from django.urls import include, path
from .views import StudentCourseList, TeacherCourseList, CourseOfferingDetail, CourseEnrollmentDetail, CourseEnrollmentList

app_name = 'course'
urlpatterns = [
    path("students/<int:st_pk>/", StudentCourseList.as_view(), name="student_course_list"),
    path("teachers/<int:teacher_pk>/", TeacherCourseList.as_view(), name="teacher_course_list"),
    path("courses/<int:c_pk>/", CourseOfferingDetail.as_view(), name="course_detail"),
    path("courses/<int:c_pk>/course-enrollments/", CourseEnrollmentList.as_view(), name="course_enrollment_list"),
    path("courses/<int:c_pk>/course-enrollments/<int:ce_pk>/", CourseEnrollmentDetail.as_view(), name="course_enrollment_detail"),
]

course/urls.py
from django.urls import include, path
from .views import CourseListView, CourseDetailView, CoursePeopleEditView, CoursePeopleView
from assignment.urls import urlpatterns as assignment_urlpatterns

app_name = 'course'
urlpatterns = [
    path('', CourseListView.as_view(), name='index'),
    path('<str:slug>/', include([
        path('', CourseDetailView.as_view(), name='detail'),
        path('p/', CoursePeopleView.as_view(), name='people'),
        path('<int:username>', CoursePeopleEditView.as_view(), name='student'),
        path('w/', include('assignment.urls', namespace='assignment')),
        path('s/', include('stream.urls', namespace='stream')),
        path('r/', include('resources.urls', namespace='resources')),
    ]))
]

saiki/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from accounts.views import HomePageView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

api_urlpatterns = [
   url(r'^', include('course.api.urls', namespace='course_api')),
   url(r'^', include('assignment.api.urls', namespace='assignment_api')),
   url(r'^', include('resources.api.urls', namespace='resources_api')),
]

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('api/', include(api_urlpatterns)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('c/', include('course.urls', namespace='course')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts1/', include('allauth.urls')),
    path('announcement/', include('announcement.urls', namespace='announcement')),
    path(r'comments/', include('django_comments_xtd.urls')),
    path(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('r/', include('result.urls', namespace='result')),
    path('w/', include('assignment.urls', namespace='assignment')),
    path('admin/', admin.site.urls),
    path('avatar/', include('avatar.urls')),
    url('^inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

admin.site.site_header = "Saiki Administration"
admin.site.site_title = "Saiki Administration Portal"
admin.site.index_title = "Welcome to Saiki Administration Portal"

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.urls.base import reverse
from django.utils.translation import ugettext as _
from shortuuidfield import ShortUUIDField
from notifications.signals import notify
from guardian.shortcuts import assign_perm
from django.urls import reverse
from meta.models import ModelMeta
from saiki.utils import get_site_title

import accounts.models
import university.models
import result.models 
import resources.models 

# Create your models here.
class Course(models.Model):
    code = models.CharField(_('code'), max_length=128, primary_key=True)
    description = models.CharField(_('description'), max_length=128)
    units = models.FloatField(_('units'))
    prereq_course = models.ForeignKey('Course', on_delete=models.CASCADE, blank=True, null=True)
    department = models.ForeignKey('university.Department', on_delete=models.CASCADE)

    def __str__(self):
        return '{} ({})'.format(self.description, self.code)

class CourseOffering(ModelMeta, models.Model):
    term = models.ForeignKey('university.Term', on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey('accounts.Teacher', on_delete=models.CASCADE)
    slug = ShortUUIDField(unique=True, editable=False)
    archive = models.BooleanField(_("Archive"), default=False)

    _metadata = {
        'title': 'get_meta_course_code',
        'description': 'get_meta_course_desc',
    }


    def get_meta_course_code(self):
        return get_site_title(self.course.code)

    def get_meta_course_desc(self):
        return self.course.description

    def get_absolute_url(self):
        return reverse('course:detail', kwargs={ 'slug': self.slug })

    class Meta:
        ordering = ['-term__year', '-term__half', 'course__code']

    def __str__(self):
        return '{} - {}'.format(self.course.code, self.term)


def courseoffering_save_handler(sender, instance, created, **kwargs):
    # add permission to teacher, so only teacher can edit and view this assignment
    if created:
        assign_perm('view_courseoffering', instance.teacher.user, instance)
        assign_perm('change_courseoffering', instance.teacher.user, instance)

        resources.models.ResourceFolder(course_offering=instance, name=str(instance), user=instance.teacher.user).save()

post_save.connect(courseoffering_save_handler, sender=CourseOffering)

class CourseEnrollment(models.Model):
    course_offered = models.ForeignKey(CourseOffering, on_delete=models.CASCADE)
    student = models.ForeignKey('accounts.Student', on_delete=models.CASCADE)
    is_hidden = models.BooleanField(default=False)

    def __str__(self):
        return '{} enrolled in {}'.format(self.student, self.course_offered)

def course_enrollment_save_handler(sender, instance, created, **kwargs):
    # users = accounts.models.User.objects.filter(student__courseenrollment__course_offered=instance.course_offering)
    user = accounts.models.User.objects.filter(pk=2)[0] # action taken by (admin can only perform these actions)
    href = reverse('course:detail', kwargs={'slug': instance.course_offered.slug})

    # give permission to student to view course

    if created:
        assign_perm('view_courseoffering', instance.student.user, instance.course_offered)

        assign_perm('change_courseenrollment', instance.student.user, instance)
        assign_perm('view_courseenrollment', instance.student.user, instance)

        result.models.Grade(course_enrollment=instance).save()

        description = f'enrolled you in { instance.course_offered.course.code }'
        notify.send(user, verb='enrolled', recipient=instance.student.user, action_object=instance, target=instance.course_offered, description=description, href=href)


def course_enrollment_delete_handler(sender, instance, *args, **kwargs):
    user = accounts.models.User.objects.filter(pk=2)[0] # action taken by (admin can only perform these actions)
    
    description = f'unenrolled you from { instance.course_offered.course.code }'
    notify.send(user, verb='unenrolled', recipient=instance.student.user, action_object=instance, target=instance.course_offered, description=description)

post_save.connect(course_enrollment_save_handler, sender=CourseEnrollment)
post_delete.connect(course_enrollment_delete_handler, sender=CourseEnrollment)

result/models.py
from result.utils import SemesterGradeHelper
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext as _
from guardian.shortcuts import assign_perm

import university.models
import accounts.models
import course.models

class Grade(models.Model):

    GRADE_POINT_EQUIVALENT = (
        (4.00, 'A'),
        (3.67, 'A-'),
        (3.33, 'B+'),
        (3.00, 'B'),
        (2.67, 'B-'),
        (2.33, 'C+'),
        (2.00, 'C'),
        (1.67, 'D'),
        (0.00, 'F'),
    )

    letter_grade = models.FloatField(_('grade'), choices=GRADE_POINT_EQUIVALENT, blank=True, null=True)
    course_enrollment = models.ForeignKey('course.CourseEnrollment', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return '{} - {}'.format(self.course_enrollment.student.user, self.course_enrollment.course_offered.course.code)

def grade_save_handler(sender, instance, created, **kwargs):
    if created:
        assign_perm('view_grade', instance.course_enrollment.student.user, instance)
        
        assign_perm('view_grade', instance.course_enrollment.course_offered.teacher.user, instance)
        assign_perm('change_grade', instance.course_enrollment.course_offered.teacher.user, instance)
    
    s, _created = SemesterGrade.objects.get_or_create(student=instance.course_enrollment.student, term=instance.course_enrollment.course_offered.term)
    s.semester_gpa = SemesterGradeHelper.get_sgpa(s)
    s.save(force_update=True)

post_save.connect(grade_save_handler, sender=Grade)

class SemesterGrade(models.Model):

    semester_gpa = models.FloatField(_("semester gpa"), blank=True, null=True)
    term = models.ForeignKey('university.Term', on_delete=models.CASCADE)
    student = models.ForeignKey('accounts.Student', on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.term)   

def semestergrade_save_handler(sender, instance, created, **kwargs):
    if created:
        assign_perm('view_semestergrade', instance.student.user, instance)

post_save.connect(semestergrade_save_handler, sender=SemesterGrade)

course/forms.py
from django import forms

class GradeForm(forms.Form):

    GRADE_POINT_EQUIVALENT = (
        (None, 'Select Grade'),
        (4.00, 'A'),
        (3.67, 'A-'),
        (3.33, 'B+'),
        (3.00, 'B'),
        (2.67, 'B-'),
        (2.33, 'C+'),
        (2.00, 'C'),
        (1.67, 'D'),
        (0.00, 'F'),
    )

    grade = forms.FloatField(widget=forms.Select(choices=GRADE_POINT_EQUIVALENT, attrs={'class': 'form-control'}), required=False)

course/api/views.py
from rest_framework import generics
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.reverse import reverse
from collections import OrderedDict
from saiki.utils import get_course_color
from course.models import CourseOffering, CourseEnrollment
from .serializers import CourseOfferingSerializer, CourseEnrollmentSerializer

class StudentCourseList(APIView):
    
    def get(self, request, st_pk):
        queryset = CourseOffering.objects.filter(courseenrollment__student_id=st_pk)
        data = []

        for course in queryset:
            color = get_course_color(course.course.code)
            d = OrderedDict()
            d['id'] = course.pk
            d['slug'] = course.slug
            d['description'] = course.course.description
            d['term'] = str(course.term)
            d['code'] = course.course.code
            ce = course.courseenrollment_set.get(student_id=st_pk)
            d['request_url'] = reverse('course_api:course_enrollment_detail', kwargs={'c_pk': course.pk, 'ce_pk': ce.pk})
            d['is_hidden'] = ce.is_hidden
            d['href'] = reverse('course:detail', kwargs={'slug': course.slug})
            d['color_bg'] = color[0]
            d['color_fg'] = color[1]
            
            data.append(d)

        return Response(data)

class TeacherCourseList(APIView):
    def get(self, request, teacher_pk):
        queryset = CourseOffering.objects.filter(teacher_id=teacher_pk)
        data = []

        for course in queryset:
            color = get_course_color(course.course.code)

            d = OrderedDict()
            d['id'] = course.pk
            d['slug'] = course.slug
            d['description'] = course.course.description
            d['term'] = str(course.term)
            d['code'] = course.course.code
            d['request_url'] = reverse('course_api:course_detail', kwargs={'c_pk': course.pk})
            d['is_hidden'] = course.archive
            d['href'] = reverse('course:detail', kwargs={'slug': course.slug})
            d['color_bg'] = color[0]
            d['color_fg'] = color[1]
            
            data.append(d)

        return Response(data)

class CourseOfferingDetail(generics.RetrieveUpdateAPIView):
    queryset = CourseOffering.objects.all()
    serializer_class = CourseOfferingSerializer
    lookup_url_kwarg = 'c_pk'

class CourseEnrollmentList(generics.ListAPIView):
    def get_queryset(self):
        queryset = CourseEnrollment.objects.filter(course_offered_id=self.kwargs['c_pk'])

        return queryset
    # queryset = CourseEnrollment.objects.all()
    # lookup_url_kwarg = 'c_pk'
    # lookup_kwarg = 'course_offered_pk'
    serializer_class = CourseEnrollmentSerializer

class CourseEnrollmentDetail(generics.RetrieveUpdateAPIView):
    def get_queryset(self):
        return CourseEnrollment.objects.filter(course_offered_id=self.kwargs['c_pk'])
    serializer_class = CourseEnrollmentSerializer
    lookup_url_kwarg = 'ce_pk'

templates/course/course_card.html
{% load saiki_extras %}

<div class="col-lg-3">
{% course_color course_off.course.code as color %}
    <div class="card" style="background: {{ color.0 }}">
        <div class="card-body">
            <h3 class="card-title text-{{color.1}} mb-3">{{ course_off.course.description }}</h3>
            <h5 class="card-text text-{{color.1}} mb-4">{{ course_off.course.code }} - {{ course_off.term }}</h5>
            <div class="position-relative">
            <a href="{% url 'course:detail' course_off.slug %}" class="btn btn-sm btn-{% if color.1 == "default" %}default{% else %}secondary{% endif %}">View Course </a>
            <a class="position-absolute right-0 p-1 text-sm text-{{ color.1 }}" href="#" id="dropdown-{{ course_off.course.code }}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-h"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdown-{{ course_off.slug }}">
                {% include './course_hide_form.html' %}
            </div>
            </div>
        </div>
    </div>
</div>

templates/course/course_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% include '../includes/header_course.html' %}

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-lg-7 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h2 class="h2">Welcome to {{ course.course.code }}</h3>
                    <h4>Instructor:</h4>
                    <p class="text-sm font-weight-normal">{{ course.teacher.user.first_name }} {{ course.teacher.user.last_name }}</p>
                    <h4>Description:</h4>
                    <p class="text-sm font-weight-normal">{{ course.course.description }}</p>
                    <h4>Term:</h4>
                    <p class="text-sm font-weight-normal">{{ course.term }}</p>
                    <h4>Code:</h4>
                    <p class="text-sm font-weight-normal">{{ course.course.code }}</p>
                    <h4>Status:</h4>
                    <p class="text-sm font-weight-normal">{{ course.archive|yesno:"Archived,Active" }}</p>
                    <p class="text-xs font-weight-normal">good luck ;)</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/course/course_list.html
{% extends "base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block content %}
{% comment %} 
// replace with react app
{% if is_student %}
    {% include '../includes/header.html' with heading=courses_offering|yesno:"My courses, Hidden courses" %}
{% endif %}

{% if is_teacher %}
    {% include '../includes/header.html' with heading=courses_offering|yesno:"My courses, Archived courses" %}
{% endif %}

{% if is_student %}
    {% include './course_list_student.html' %}
{% elif is_teacher %}
    {% include './course_list_teacher.html' %}
{% endif %}
 {% endcomment %}

<div id="course-app"></div>
{% endblock %}

{% block script_2 %}
<script src="https://unpkg.com/react@17/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js" crossorigin></script>

<script>
window.course_list_app_props = {
    {% if is_student %}
    request_url: '{% url 'course_api:student_course_list' student.pk %}',
    {% elif is_teacher %}
    request_url: '{% url 'course_api:teacher_course_list' teacher.pk %}',
    {% endif %}
    is_student: {{ is_student|yesno:"true,false" }}
};
Object.freeze(window.course_list_app_props);
</script>

{% render_bundle 'course' 'js' %}
{% render_bundle 'vendors' 'js' %}

{% endblock %}

templates/course/course_list_student.html
<div class="container-fluid mt--6">
{% if courses_offering %}
    <div class="row">
        {% for course_off in courses_offering %}
            {% include './course_card.html' %}
        {% endfor %}
    </div>

{% if hidden_courses %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="w-100 text-left h3" data-toggle="collapse" data-target="#collapseArchive" aria-expanded="false" aria-controls="collapseArchive">
        Hidden courses
            <i class="ni ni-bold-down float-right"></i>
        </h1>
    </div>
    <div class="row collapse" id="collapseArchive">
{% endif %}

{% else %}
    <div class="row">
{% endif %}
        {% for course_off in hidden_courses %}
            {% include './course_card.html' %}
        {% endfor %}
    </div>
</div>


<div class="container-fluid mt--6">
{% if courses_offering %}
<div class="row">
    {% for course_off in courses_offering %}
        {% include './course_card.html' %}
    {% endfor %}
</div>
{% endif %}

{% if hidden_courses and courses_offering %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
<h1 class="w-100 text-left h3" data-toggle="collapse" data-target="#collapseArchive" aria-expanded="false" aria-controls="collapseArchive">
    Hidden courses<i class="ni ni-bold-down float-right"></i>
</h1>
</div>
<div class="row collapse" id="collapseArchive">
{% for course_off in hidden_courses %}
    {% include './course_card.html' %}
{% endfor %}
</div>
{% elif hidden_courses %}
<div class="row">
    {% for course_off in hidden_courses %}
        {% include './course_card.html' %}
    {% endfor %}
</div>
{% endif %}

</div>

templates/course/course_list_teacher.html
<div class="container-fluid mt--6">
    <div class="row">
        {% for course_off in courses_offering %}
            {% include './course_card.html' %}
        {% endfor %}
    </div>
</div>

templates/course/course_people_edit.html
{% extends "base.html" %} 
{% load static %} 
{% block content %} 

{% include '../includes/header_course.html' %}

<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-lg-7 mx-auto">
      <div class="card">
        <div class="card-header">
          <h3 class="mb-0">
            {{ student_.user.first_name }} {{ student_.user.last_name }} - {{ student_.user.username }}
          </h3>
        </div>
        <div class="card-body">
          <form class="needs-validation" action="" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <div class="form-group">
                  <label class="form-control-label" for="{{ form.grade.id_for_label }}">Grade:</label>
                  {{ form.grade }}
                </div>
              </div>
            </div>
            <button class="btn btn-primary" type="submit">Save changes</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/course/course_people_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% include '../includes/header_course.html' %}
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-lg-7 mx-auto">
            {% include './course_people_list_table.html' %}
        </div>
    </div>
</div>
{% endblock %}

templates/course/course_people_list_table.html
{% load avatar_tags %}

<div class="card">
  <div class="card-header border-0">
    <div class="row">
      <div class="col-6">
        <h3 class="mb-0">Teachers</h3>
      </div>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table align-items-center table-flush table-striped">
      <thead class="thead-light">
        <tr>
          <th class="w-auto">Name</th>
        </tr>
      </thead>
      <tbody>
        <tr>
            <td class="table-user">
            {% avatar course.teacher.user 240 class="avatar rounded-circle mr-3" %}
            <b>{{ course.teacher.user.first_name }} {{ course.teacher.user.last_name }}</b>
            </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% if students.count > 1 or is_teacher %}
<div class="card">
  <div class="card-header border-0">
    <div class="row">
      <div class="col-6">
        {% if is_student %}
            <h3 class="mb-0">Classmates</h3>
        {% else %}
            <h3 class="mb-0">Students</h3>
        {% endif %}
      </div>
      <div class="col-6 text-right">
        {% if is_student %}
          <p class="mb-0 text-sm font-weight-bold">{{ students.count }} classmate{{ students.count|pluralize }}</h3>
        {% else %}
            <p class="mb-0 text-sm font-weight-bold">{{ students.count }} student{{ students.count|pluralize }}</h3>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table align-items-center table-flush table-striped">
      <thead class="thead-light">
        <tr>
          <th class="w-auto">Name</th>
          {% if is_teacher %}
            <th class="w-10">ID</th>
            <th class="w-10">Program</th>
            <th class="w-10">Grade</th>
            <th class="w-10"></th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
      {% for student in students %}
        <tr>
          <td class="table-user">
            {% avatar student.user 240 class="avatar rounded-circle mr-3" %}
            <b>{{ student.user.first_name }} {{ student.user.last_name }}</b>
          </td>
          {% if is_teacher %}
          <td>
            <span class="text-muted">{{ student.user.username }}</span>
          </td>
          <td>
            <span class="text-muted">{{ student.program.code }}</span>
          </td>
          <td>
            {% for ce in student.courseenrollment_set.all %}
              {% for grade in ce.grade_set.all %}
                {% if grade.course_enrollment.course_offered == course %}
                    {% include '../result/letter_grade.html' %}
                {% endif %}
              {% endfor %}
            {% endfor %}
          </td>
          <td class="table-actions">
            <a href="{% url 'course:student' course.slug student.user.username %}" class="table-action" data-toggle="tooltip" data-original-title="Edit grade">
              <i class="fas fa-user-edit"></i>
            </a>
            {% if student.user.email %}
                <a href="mailto:{{student.user.email}}" class="table-action" data-toggle="tooltip" data-original-title="Email {{student.user.email}}">
                <i class="fas fa-envelope"></i>
                </a>
            {% endif %}
          </td>
          {% endif %}
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endif %}