assignment/api/urls.py
from django.urls import include, path
from .views import AssignmentWorkDetail, AssignmentWorkFileList, AssignmentWorkFileDetail, AssignmentFileList, AssignmentFileDetail

app_name = 'assignment'
urlpatterns = [
    path("assignments/<int:assignment_pk>/materials/", AssignmentFileList.as_view(), name="assignment_file_list"),
    path("assignments/<int:assignment_pk>/materials/<int:material_pk>", AssignmentFileDetail.as_view(), name="assignment_file_detail"),
    
    path("assignmentworks/<int:assignmentwork_pk>/", AssignmentWorkDetail.as_view(), name="assignment_detail"),
    path("assignmentworks/<int:assignmentwork_pk>/work-materials/", AssignmentWorkFileList.as_view(), name="assignment_work_file_list"),
    path("assignmentworks/<int:assignmentwork_pk>/work-materials/<int:workmaterial_pk>", AssignmentWorkFileDetail.as_view(), name="assignment_work_file_detail"),
]

assignment/urls.py
from django.urls import include, path
from .views import AssignmentAssignPointView, AssignmentDeleteView, AssignmentEditUploadView, AssignmentListView, AssignmentDetailView, AssignmentCreateView, AssignmentEditView

app_name = 'assignment'
urlpatterns = [
    path('', AssignmentListView.as_view(), name='index'),
    path('create/', AssignmentCreateView.as_view(), name='create'),
    path('<uuid:slug>/', include([
        path('', AssignmentDetailView.as_view(), name='detail'),
        path('edit/', include([
            path('', AssignmentEditView.as_view(), name='edit'),
            path('upload/', AssignmentEditUploadView.as_view(), name='edit_upload'),
        ])),
        path('delete/', AssignmentDeleteView.as_view(), name='delete'),
        path('<int:username>', AssignmentAssignPointView.as_view(), name='assign_student_point'),
    ]))
]

saiki/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from accounts.views import HomePageView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

api_urlpatterns = [
   url(r'^', include('course.api.urls', namespace='course_api')),
   url(r'^', include('assignment.api.urls', namespace='assignment_api')),
   url(r'^', include('resources.api.urls', namespace='resources_api')),
]

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('api/', include(api_urlpatterns)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('c/', include('course.urls', namespace='course')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts1/', include('allauth.urls')),
    path('announcement/', include('announcement.urls', namespace='announcement')),
    path(r'comments/', include('django_comments_xtd.urls')),
    path(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('r/', include('result.urls', namespace='result')),
    path('w/', include('assignment.urls', namespace='assignment')),
    path('admin/', admin.site.urls),
    path('avatar/', include('avatar.urls')),
    url('^inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

admin.site.site_header = "Saiki Administration"
admin.site.site_title = "Saiki Administration Portal"
admin.site.index_title = "Welcome to Saiki Administration Portal"

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/models.py
import datetime
import os
import uuid

import accounts.models
import course.models
import stream.models
from django.db import models
from django.db.models.signals import post_delete, post_save, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import ugettext as _
from guardian.shortcuts import assign_perm
from meta.models import ModelMeta
from notifications.signals import notify
from saiki.utils import get_site_title

from .utils import file_cleanup

""" Whenever ANY model is deleted, if it has a file field on it, delete the associated file too"""
@receiver(post_delete)
def delete_files_when_row_deleted_from_db(sender, instance, **kwargs):
    for field in sender._meta.concrete_fields:
        if isinstance(field,models.FileField):
            instance_file_field = getattr(instance,field.name)
            delete_file_if_unused(sender,instance,field,instance_file_field)

""" Delete the file if something else get uploaded in its place"""
@receiver(pre_save)
def delete_files_when_file_changed(sender,instance, **kwargs):
    # Don't run on initial save
    if not instance.pk:
        return
    for field in sender._meta.concrete_fields:
        if isinstance(field,models.FileField):
            #its got a file field. Let's see if it changed
            try:
                instance_in_db = sender.objects.get(pk=instance.pk)
            except sender.DoesNotExist:
                # We are probably in a transaction and the PK is just temporary
                # Don't worry about deleting attachments if they aren't actually saved yet.
                return
            instance_in_db_file_field = getattr(instance_in_db,field.name)
            instance_file_field = getattr(instance,field.name)
            if instance_in_db_file_field.name != instance_file_field.name:
                delete_file_if_unused(sender,instance,field,instance_in_db_file_field)


""" Only delete the file if no other instances of that model are using it"""    
def delete_file_if_unused(model,instance,field,instance_file_field):
    dynamic_field = {}
    dynamic_field[field.name] = instance_file_field.name
    other_refs_exist = model.objects.filter(**dynamic_field).exclude(pk=instance.pk).exists()
    if not other_refs_exist:
        instance_file_field.delete(False)

class Assignment(ModelMeta, models.Model):

    title = models.CharField(_('title'), max_length=256)
    description = models.TextField(_('description'), blank=True, null=True, max_length=256)
    deadline = models.DateTimeField(_("deadline"))
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    course_offering = models.ForeignKey('course.CourseOffering', on_delete=models.CASCADE)
    slug = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    points = models.PositiveIntegerField(_("points"), default=0)

    _metadata = {
        'title': 'get_meta_assignment_title',
        'description': 'get_meta_assignment_description',
    }

    def get_meta_assignment_title(self):
        return get_site_title(f'{ self.title } - { self.course_offering.course.code }')

    def get_meta_assignment_description(self):
        return self.description[:120] + (self.description[120:] and '..')

    def __str__(self):
        return '{} - {}'.format(self.course_offering, self.title)

    def get_absolute_url(self):
        return reverse('assignment:detail', kwargs={ 'slug': self.slug })

    @property
    def is_not_in_deadline(self):
        return self.deadline < datetime.datetime.now(self.deadline.tzinfo)

def assignment_save_handler(sender, instance, created, **kwargs):
    # users who can view assignment
    users = accounts.models.User.objects.filter(student__courseenrollment__course_offered=instance.course_offering)

    # add permission to teacher, so only teacher can edit and view this assignment
    if created:
        assign_perm('add_assignment', instance.course_offering.teacher.user, instance)
        assign_perm('change_assignment', instance.course_offering.teacher.user, instance)
        assign_perm('delete_assignment', instance.course_offering.teacher.user, instance)
        assign_perm('view_assignment', instance.course_offering.teacher.user, instance)

        assign_perm('view_assignment', users, instance)

        post = stream.models.Post()
        post.stream = instance.course_offering
        post.user = instance.course_offering.teacher.user
        post.body = f'Assignment: { instance.title }'
        post.post_type = 'assignment'
        post.assignment = instance
        post.save()

        verb = 'assigned'
    else:
        verb = 'updated'
    
    description = f'{ verb } <b>{ instance.title }</b> in { instance.course_offering.course.code }'
    href = reverse('assignment:detail', kwargs={'slug': instance.slug})
    notify.send(instance.course_offering.teacher.user, verb='updated', recipient=users, action_object=instance, target=instance.course_offering, description=description, href=href)

def assignment_delete_handler(sender, instance, *args, **kwargs):
    users = accounts.models.User.objects.filter(student__courseenrollment__course_offered=instance.course_offering)
    
    description = f'deleted <b>{ instance.title }</b> in { instance.course_offering.course.code }'
    notify.send(instance.course_offering.teacher.user, verb='deleted', recipient=users, action_object=instance, target=instance.course_offering, description=description)

post_save.connect(assignment_save_handler, sender=Assignment)
post_delete.connect(assignment_delete_handler, sender=Assignment)

def upload_path(instance, filename):
    return os.path.join('assignment', str(instance.assignment.slug), filename)

class AssignmentFile(models.Model):
    file = models.FileField(upload_to=upload_path)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, null=True, blank=True)

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension[1:]

    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return '{} - {}'.format(self.assignment, self.file.name)

class AssignmentWork(models.Model):

    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    student = models.ForeignKey('accounts.Student', on_delete=models.CASCADE)
    submit_date = models.DateTimeField(_("submit date"), blank=True, null=True)
    submitted = models.BooleanField(_("submitted"), default=False)
    points = models.IntegerField(_("points"), default=-1, null=True, blank=True)

    @property
    def is_submitted_on_time(self):
        return self.submit_date < self.assignment.deadline

    def __str__(self):
        return '{} - {}'.format(self.assignment, self.student)


def assignmentwork_save_handler(sender, instance, created, **kwargs):
    if created:
        assign_perm('change_assignmentwork', instance.assignment.course_offering.teacher.user, instance)
        assign_perm('view_assignmentwork', instance.assignment.course_offering.teacher.user, instance)
        
        assign_perm('change_assignmentwork', instance.student.user, instance)
        assign_perm('view_assignmentwork', instance.student.user, instance)

post_save.connect(assignmentwork_save_handler, sender=AssignmentWork)

def upload_work_path(instance, filename):
    return os.path.join('assignment' , str(instance.assignment_work.assignment.slug), 'work', str(instance.assignment_work.student.user.username), filename)

class AssignmentWorkFile(models.Model):
    file = models.FileField(upload_to=upload_work_path)
    assignment_work = models.ForeignKey(AssignmentWork, on_delete=models.CASCADE, null=True, blank=True)

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension[1:]

    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return '{} - {}'.format(self.assignment_work, self.file.name)

assignment/api/views.py
from rest_framework import generics
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.reverse import reverse
from collections import OrderedDict
from saiki.utils import get_course_color
from assignment.models import Assignment, AssignmentWork, AssignmentFile, AssignmentWorkFile
from .serializers import AssignmentSerializer, AssignmentWorkSerializer, AssignmentFileSerializer, AssignmentWorkFileSerializer
from rest_framework.reverse import reverse
from rest_framework import status

class AssignmentWorkDetail(generics.RetrieveUpdateAPIView):
    
    def get(self, request, assignmentwork_pk):
        queryset = AssignmentWork.objects.filter(pk=assignmentwork_pk)
        d = OrderedDict()

        for a in queryset:
            d['id'] = a.pk
            d['submit_date'] = a.submit_date
            d['submitted'] = a.submitted
            d['points'] = a.points
            d['assignment'] = a.assignment
            d['student'] = a.student
            d['title'] = a.assignment.title
            d['deadline'] = a.assignment.deadline
            d['description'] = a.assignment.description
            d['course_offering'] = a.assignment.course_offering.pk

            materials = AssignmentFile.objects.filter(assignment=a.assignment)
            d['materials'] = [m.file for m in materials]

            work_materials = AssignmentWorkFile.objects.filter(assignment_work=a)
            print(work_materials)
            d['work_material_urls'] = [
                reverse('assignment_api:assignment_work_file_detail', kwargs={'assignmentwork_pk': a.pk, 'workmaterial_pk': m.pk}) for m in work_materials]

        serializer = AssignmentWorkSerializer(d)

        return Response(serializer.data)
    
    queryset = AssignmentWork.objects.all()
    serializer_class = AssignmentWorkSerializer
    lookup_url_kwarg = 'assignmentwork_pk'

class AssignmentWorkFileList(generics.ListCreateAPIView):
    serializer_class = AssignmentWorkFileSerializer
    page_size = 100

    def get(self, request, assignmentwork_pk):
        queryset = AssignmentWorkFile.objects.filter(assignment_work_id=assignmentwork_pk)
        data = []

        for a in queryset:
            d = OrderedDict()
            
            d['id'] = a.pk
            d['file'] = a.file
            d['assignment_work'] = a.assignment_work
            d['request_url'] = reverse('assignment_api:assignment_work_file_detail', kwargs={'assignmentwork_pk': a.assignment_work.pk, 'workmaterial_pk': a.pk})

            data.append(d)

        serializer = AssignmentWorkFileSerializer(data, many=True)

        return Response(serializer.data)


    def get_queryset(self):
        queryset = AssignmentWorkFile.objects.filter(assignment_work_id=self.kwargs['assignmentwork_pk'])
        return queryset


class AssignmentWorkFileDetail(generics.RetrieveDestroyAPIView):
    serializer_class = AssignmentWorkFileSerializer
    lookup_url_kwarg = 'workmaterial_pk'

    def get(self, request, assignmentwork_pk, workmaterial_pk):
        queryset = AssignmentWorkFile.objects.filter(id=workmaterial_pk)
        d = OrderedDict()

        for a in queryset:

            d['id'] = a.pk
            d['file'] = a.file
            d['assignment_work'] = a.assignment_work
            d['request_url'] = reverse('assignment_api:assignment_work_file_detail', kwargs={'assignmentwork_pk': a.assignment_work.pk, 'workmaterial_pk': a.pk})

        serializer = AssignmentWorkFileSerializer(d)

        return Response(serializer.data)

    def get_queryset(self):
        queryset = AssignmentWorkFile.objects.filter(assignment_work_id=self.kwargs['assignmentwork_pk'])
        return queryset

class AssignmentFileList(generics.ListCreateAPIView):
    serializer_class = AssignmentFileSerializer
    page_size = 100

    def get(self, request, assignment_pk):
        queryset = AssignmentFile.objects.filter(assignment_id=assignment_pk)
        data = []

        for a in queryset:
            d = OrderedDict()
            
            d['id'] = a.pk
            d['file'] = a.file
            d['assignment'] = a.assignment
            d['request_url'] = reverse('assignment_api:assignment_file_detail', kwargs={'assignment_pk': a.assignment.pk, 'material_pk': a.pk})

            data.append(d)

        serializer = AssignmentFileSerializer(data, many=True)

        return Response(serializer.data)


    def get_queryset(self):
        queryset = AssignmentFile.objects.filter(assignment_id=self.kwargs['assignment_pk'])
        return queryset

class AssignmentFileDetail(generics.RetrieveDestroyAPIView):
    serializer_class = AssignmentFileSerializer
    lookup_url_kwarg = 'material_pk'

    def get(self, request, assignment_pk, material_pk):
        queryset = AssignmentFile.objects.filter(id=material_pk)
        d = OrderedDict()

        for a in queryset:

            d['id'] = a.pk
            d['file'] = a.file
            d['assignment'] = a.assignment
            d['request_url'] = reverse('assignment_api:assignment_file_detail', kwargs={'assignment_pk': a.assignment.pk, 'material_pk': a.pk})

        serializer = AssignmentFileSerializer(d)

        return Response(serializer.data)

    def get_queryset(self):
        queryset = AssignmentFile.objects.filter(assignment_id=self.kwargs['assignment_pk'])
        return queryset

templates/assignment/assignment.html
{% extends "base.html" %}

{% block title%}Assignments - Saiki{% endblock %}

{% block content %}

<!-- Header -->
{% if course %}


{% include '../includes/header_course.html' %}

{% else %}

{% include '../includes/header.html' with heading="Assignments" %}

{% endif %}

<div class="container-fluid mt--6">
    {% if is_student %}
    {% include './assignment_s.html' %}
    {% elif is_teacher %}
    {% include './assignment_t.html' %}
    {% endif %}
</div>
{% endblock %}

templates/assignment/assignment_assign_point.html
{% extends "base.html" %} 
{% load static %} 
{% load saiki_extras %} 

{% block style %}
<link
  type="text/css"
  href="{% static '/css/file-icon-square-o.min.css' %}"
  rel="stylesheet"
/>
{% endblock %} 

{% block content %} 

{% url 'assignment:detail' assignment.slug as assignment_view_url %}
{% with assignment.deadline|date:"F d, Y f A" as assignment_deadline %}
{% include '../includes/header.html' with heading=assignment.title subheading="Due "|addstr:assignment_deadline btn1_url=assignment_view_url btn1_title="View all submissions" %}
{% endwith %}

<div class="container-fluid mt--6">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
            <div class="d-flex mb-0 position-relative">
              <h3 class="mb-0">
                <span class="">{{ student_.user.first_name }} {{ student_.user.last_name }} - {{ student_.user.username }}</span>
              </h3>
              {% if assignment_work.is_submitted_on_time %}
              <span class="text-xs position-absolute right-0 text-gray font-weight-bold">
              Submitted on {{ assignment_work.submit_date|date:"F d, Y f A" }}</span>
              {% else %}
              <span class="text-xs position-absolute right-0 text-danger font-weight-bold">
              Submitted on {{ assignment_work.submit_date|date:"F d, Y f A" }} (Late)</span>
              {% endif %}    
              </span>
            </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <h4>Instruction</h4>
              <p class="text-sm">
                {% if assignment.description|length > 0 %} 
                {{ assignment.description|safe }} 
                {% else %}
                <em>None</em>
                {% endif %}
              </p>
              <h4 class="mt-3">Reference material</h4>
              <ul class="material">
                {% for material in materials %}
                <li class="mb-2">
                  <a href="{{ material.file.url }}" target="_blank">
                    <span
                      class="fiv-sqo fiv-icon-{{ material.extension }}"
                    ></span>
                    <span class="text-sm font-weight-bold text-dark"
                      >{{ material.filename }}</span
                    >
                  </a>
                </li>
                {% endfor %}
              </ul>
              <h4 class="mt-3">Student files</h4>
              <ul class="material">
                {% for work_file in submission %}

                <li class="mb-2">
                  <a
                    href="{{ work_file.file.url }}"
                    target="_blank"
                    class="position-relative"
                  >
                    <span
                      class="fiv-sqo fiv-icon-{{ work_file.extension }}"
                    ></span>
                    <span
                      class="text-sm font-weight-bold text-dark"
                      data-dz-name
                      >{{ work_file.filename }}</span
                    >
                  </a>
                </li>

                {% endfor %}
              </ul>
            </div>
            <div class="col-lg-6">
              <h4>Points</h4>
              {% if assignment.points != 0 %}
              <form action="" method="POST">
                {% csrf_token %}
               <input type="number" name="points" value="{{ assignment_work.points }}" class="col-2 form-control d-inline-block form-control-sm" min="-1" id="id_points" max="{{ assignment.points }}">
               <span class="font-weight-bold text-sm">out of {{ assignment.points }}</span>
               <br>
               <button type="submit" class="mt-3 btn btn-primary btn-sm">Assign points</button>
              </form>
              {% else %}
                <span class="font-weight-bold font-italic text-sm">No points</span>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/assignment/assignment_detail.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load static %}
{% load avatar_tags %}
{% load saiki_extras %}

{% block title%}Announcement - Saiki{% endblock %}
{% comment %} {% block script_1 %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
{% endblock %}
 {% endcomment %}
{% block style %}
<link type="text/css" href="{% static '/css/file-icon-square-o.min.css' %}" rel="stylesheet" >
{% endblock %}

{% block content %}
{% if is_student %}
	{% include '../includes/header_ad.html' %}
{% elif is_teacher %}
	{% url 'assignment:edit' assignment.slug as assignment_edit_url %}
	{% url 'assignment:delete' assignment.slug as assignment_delete_url %}
	{% with assignment.deadline|date:"F d, Y f A" as assignment_deadline %}
	{% include '../includes/header.html' with heading=assignment.title subheading="Due "|addstr:assignment_deadline btn1_url=assignment_edit_url btn1_title="Edit" btn2_url=assignment_delete_url btn2_title="Delete" %}
	{% endwith %}
{% endif %}
		

<div class="container-fluid mt--6">
   <div class="row">
        <div class="col">
{% if is_student %}
	{% include './assignment_detail_student.html' %}
{% elif is_teacher %}
	{% include './assignment_detail_teacher.html' %}
{% endif %}
		</div>
    </div>
</div>
{% endblock %}

{% block script_2 %}
{% if is_student %}
<script src="https://unpkg.com/react@17/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js" crossorigin></script>

<script>
window.material_list_app_props = {
	request_url: "{% url 'assignment_api:assignment_work_file_list' work.pk %}",
{% if work.points < 0 %}
	graded: false,
{% else %}
	graded: true,
{% endif %}
	turned: {{ turned|yesno:'true, false' }},
	page: 'assignment_work',
	page_id: {{ work.pk }}
};
Object.freeze(window.material_list_app_props);
</script>

{% render_bundle 'assignment' 'js' %}
{% render_bundle 'vendors' 'js' %}

{% endif %}
{% endblock %}

templates/assignment/assignment_detail_teacher.html
{% load avatar_tags %}

<div class="card">
  <div class="card-header border-0">
    <div class="row">
      <div class="col-6">
        <h3 class="mb-0">Submissions</h3>
      </div>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table align-items-center table-flush table-striped">
      <thead class="thead-light">
        <tr>
          <th class="w-auto">Name</th>
          <th class="w-10">ID</th>
          <th class="w-10">Program</th>
          <th class="w-10">Date</th>
          {% if assignment.points != 0 %}
            <th class="w-10">Points</th>
          {% endif %}
          <th class="w-10"></th>
        </tr>
      </thead>
      <tbody>
      {% for student in students %}
        <tr>
          <td class="table-user">
            {% avatar student.user 36 class="avatar avatar-sm rounded-circle mr-3" id="user_avatar" %}
            <b>{{ student.user.first_name }} {{ student.user.last_name }}</b>
          </td>
          <td>
            <span class="text-muted">{{ student.user.username }}</span>
          </td>
          <td>
            <span class="text-muted">{{ student.program.code }}</span>
          </td>
          <td>
            <span class="text-muted">
            {% for assignmentwork in student.assignmentwork_set.all %}
              {% if assignmentwork.assignment == assignment %}
                  {{ assignmentwork.submit_date|date:"F d, Y f A"  }}
              {% endif %}
            {% endfor %}
            </span>
          </td>
          {% if assignment.points != 0 %}
          <td>
            <span class="text-muted">
            {% for assignmentwork in student.assignmentwork_set.all %}
              {% if assignmentwork.assignment == assignment %}
                  {% if assignmentwork.points < 0 %} 
                    -
                  {% else %} 
                    {{ assignmentwork.points }}/{{ assignmentwork.assignment.points }} 
                  {% endif %}
              {% endif %}
            {% endfor %}
            </span>
          </td>
          {% endif %}
          <td class="table-actions">
            <a href="{% url 'assignment:assign_student_point' assignment.slug student.user.username %}" class="table-action" data-toggle="tooltip" data-original-title="View submission">
              <i class="fas fa-eye"></i>
            </a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td>No submissions yet.</td>
          <td></td>
          <td></td>
          <td></td>
          {% if assignment.points != 0 %}
            <td></td>
          {% endif %}
          <td></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

templates/assignment/assignment_edit.html
{% extends "base.html" %}
{% load static %}
{% load saiki_extras %}
{% load render_bundle from webpack_loader %}

{% block title%}Assignments - Saiki{% endblock %}

{% block script_1 %}
{% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script> {% endcomment %}
<script src="{% static '/vendor/quill/dist/quill.min.js' %}"></script>
{% endblock %}

{% block style %}
<link type="text/css" href="{% static '/vendor/quill/dist/quill.core.css' %}" rel="stylesheet" >
<link type="text/css" href="{% static '/css/file-icon-square-o.min.css' %}" rel="stylesheet" >
{% endblock %}

{% block content %}

{% url 'assignment:detail' assignment.slug as assignment_detail_url %}
{% url 'assignment:delete' assignment.slug as assignment_delete_url %}
{% with assignment.deadline|date:"F d, Y f A" as assignment_deadline %}
{% include '../includes/header.html' with heading=assignment.title subheading="Due "|addstr:assignment_deadline btn1_url=assignment_detail_url btn1_title="View" btn2_url=assignment_delete_url btn2_title="Delete" %}
{% endwith %}

<div class="container-fluid mt--6">
<div class="row">
    <div class="col">
      <div class="card mb-4">
        <div class="card-header">
          <h3 class="mb-0">Edit Assignment</h3>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <form action="" method="POST">
                {% csrf_token %}
                <div class="row">
                <div class="col-12">
                  <div class="form-group">
                    <label class="form-control-label">Title</label>
                    <input value="{{ assignment.title }}" type="text" class="form-control" placeholder="One of three cols" name="title" required>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="form-group">
                    <label class="form-control-label">Points</label>
                    <input type="number" class="form-control" name="points" value="{{ assignment.points }}" min="0">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-6">
                  <div class="form-group">
                    <label class="form-control-label">Deadline</label>
                    <input type="date" class="form-control" name="date" value="{{ assignment.deadline|date:"Y-m-d" }}">
                  </div>
                </div>
                <div class="col-6">
                  <div class="form-group">
                    <label class="form-control-label invisible">Deadline</label>
                    <input type="time" class="form-control" name="time" value="{{ assignment.deadline|date:"H:i" }}">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="form-group">
                    <label class="form-control-label" for="description">Instruction</label>
                    <input name="description" type="hidden" id="description" value="{{ assignment.description }}">
                    <div class="quill-initial-state d-none">{{ assignment.description|safe }}</div>
                    <div data-toggle="quill"></div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="form-group">
                    <button class="btn btn-primary" type="submit">Save changes</button>
                  </div>
                </div>
              </div>
              </form>
            </div>
            <div class="col-md-6">
                <div class="col-12">
                  <label class="form-control-label">Work materials</label>
                  <div id="material-app"></div>  
                  {% comment %} 
                    {% include './assignment_edit_material_form.html' %}
                  {% endcomment %}
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>


</div>
{% endblock %}
{% block script_2 %}
<script src="https://unpkg.com/react@17/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js" crossorigin></script>

<script>
window.material_list_app_props = {
  request_url: "{% url 'assignment_api:assignment_file_list' assignment.pk %}",
  graded: false,
  turned: false,
  page: 'assignment',
  page_id: {{ assignment.pk }}
};
Object.freeze(window.material_list_app_props);
</script>

{% render_bundle 'assignment' 'js' %}
{% render_bundle 'vendors' 'js' %}

{% endblock %}