result/urls.py
from django.urls import include, path
from .views import ResultListView, ViewMyGrades, SelectedTerm

app_name = 'result'
urlpatterns = [
    path('', ResultListView.as_view(), name='index'),
    path('terms/', include([
        path('', ViewMyGrades.as_view(), name='select_term'),
        path('<int:pk>/', SelectedTerm.as_view(), name='by_term'),
    ]))
]

saiki/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from accounts.views import HomePageView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

api_urlpatterns = [
   url(r'^', include('course.api.urls', namespace='course_api')),
   url(r'^', include('assignment.api.urls', namespace='assignment_api')),
   url(r'^', include('resources.api.urls', namespace='resources_api')),
]

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('api/', include(api_urlpatterns)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('c/', include('course.urls', namespace='course')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts1/', include('allauth.urls')),
    path('announcement/', include('announcement.urls', namespace='announcement')),
    path(r'comments/', include('django_comments_xtd.urls')),
    path(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('r/', include('result.urls', namespace='result')),
    path('w/', include('assignment.urls', namespace='assignment')),
    path('admin/', admin.site.urls),
    path('avatar/', include('avatar.urls')),
    url('^inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

admin.site.site_header = "Saiki Administration"
admin.site.site_title = "Saiki Administration Portal"
admin.site.index_title = "Welcome to Saiki Administration Portal"

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

result/models.py
from result.utils import SemesterGradeHelper
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext as _
from guardian.shortcuts import assign_perm

import university.models
import accounts.models
import course.models

class Grade(models.Model):

    GRADE_POINT_EQUIVALENT = (
        (4.00, 'A'),
        (3.67, 'A-'),
        (3.33, 'B+'),
        (3.00, 'B'),
        (2.67, 'B-'),
        (2.33, 'C+'),
        (2.00, 'C'),
        (1.67, 'D'),
        (0.00, 'F'),
    )

    letter_grade = models.FloatField(_('grade'), choices=GRADE_POINT_EQUIVALENT, blank=True, null=True)
    course_enrollment = models.ForeignKey('course.CourseEnrollment', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return '{} - {}'.format(self.course_enrollment.student.user, self.course_enrollment.course_offered.course.code)

def grade_save_handler(sender, instance, created, **kwargs):
    if created:
        assign_perm('view_grade', instance.course_enrollment.student.user, instance)
        
        assign_perm('view_grade', instance.course_enrollment.course_offered.teacher.user, instance)
        assign_perm('change_grade', instance.course_enrollment.course_offered.teacher.user, instance)
    
    s, _created = SemesterGrade.objects.get_or_create(student=instance.course_enrollment.student, term=instance.course_enrollment.course_offered.term)
    s.semester_gpa = SemesterGradeHelper.get_sgpa(s)
    s.save(force_update=True)

post_save.connect(grade_save_handler, sender=Grade)

class SemesterGrade(models.Model):

    semester_gpa = models.FloatField(_("semester gpa"), blank=True, null=True)
    term = models.ForeignKey('university.Term', on_delete=models.CASCADE)
    student = models.ForeignKey('accounts.Student', on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.term)   

def semestergrade_save_handler(sender, instance, created, **kwargs):
    if created:
        assign_perm('view_semestergrade', instance.student.user, instance)

post_save.connect(semestergrade_save_handler, sender=SemesterGrade)

result/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponseForbidden
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.list import ListView
from .models import Grade, SemesterGrade
from university.models import Term
from accounts.utils import get_current_student
from meta.views import Meta
from saiki.utils import get_site_title

class ResultListView(LoginRequiredMixin, ListView):
    redirect_field_name = 'accounts:login'
    model = Grade
    context_object_name = 'grades'
    template_name = 'result/result_detail.html'
    semester_grade = SemesterGrade.objects.all()
    cgpa = 0

    def get(self, request, *args, **kwargs):
        if not request.user.is_student:
            return HttpResponseForbidden()

        return super().get(self, request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super(ResultListView, self).get_context_data(**kwargs)
        meta = Meta(
            title=get_site_title('Results')
        )
        

        context['is_result_page'] = 'active'
        context['meta'] = meta
        context['student'] = get_current_student(self.request)
        context['semester_grades'] = self.semester_grade
        context['cgpa'] = self.cgpa
        return context

    def get_queryset(self):
        student = get_current_student(self.request)

        try:
            term = Term.objects.all()[:1].get()
        except Term.DoesNotExist:
            term = None

        #  hterm is None here so get the latest
        self.cgpa = student.get_cgpa()

        queryset = super(ResultListView, self).get_queryset()
        queryset = queryset.filter(course_enrollment__student=student, course_enrollment__course_offered__term=term)
        self.semester_grade = self.semester_grade.filter(student=student, term=term)

        return queryset

    def dispatch(self, request, *args, **kwargs):
        student = get_current_student(self.request)

        if student.is_graduated:
            return redirect('result:select_term')
        else:
            return super(ResultListView, self).dispatch(request, *args, **kwargs)

class ViewMyGrades(LoginRequiredMixin, ListView):
    redirect_field_name = 'accounts:login'
    model = SemesterGrade
    template_name='result/result_list.html'
    semester_grades = None
    term = None

    def get(self, request, *args, **kwargs):
        if not request.user.is_student:
            return HttpResponseForbidden()

        return super().get(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewMyGrades, self).get_context_data(**kwargs)
        meta = Meta(
            title=get_site_title('Select Term')
        )

        context['is_result_page'] = 'active'
        context['meta'] = meta
        
        context['student'] = get_current_student(self.request)
        context['semester_grades'] = self.semester_grades
        context['term'] = self.term
        return context

    def get_queryset(self):
        student = get_current_student(self.request)

        if not student.is_graduated:
            try:
                self.term = Term.objects.all()[:1].get()
            except Term.DoesNotExist:
                self.term = None

        self.cgpa = student.get_cgpa()
        self.semester_grades = student.get_semester_grades()
        queryset = super(ViewMyGrades, self).get_queryset()
        queryset = queryset
        return queryset

class SelectedTerm(LoginRequiredMixin, ListView):
    redirect_field_name = 'accounts:login'
    model = Grade
    context_object_name = 'grades'
    template_name = 'result/result_detail.html'
    semester_grade = SemesterGrade.objects.all()
    cgpa = 0

    def get(self, request, *args, **kwargs):
        if not request.user.is_student:
            return HttpResponseForbidden()

        return super().get(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SelectedTerm, self).get_context_data(**kwargs)
        try:
            term = Term.objects.filter(pk=self.kwargs['pk'])[:1].get()
        except Term.DoesNotExist:
            term = None
        
        title = f'Result - {term}'
        if not term:
            title = 'Result'

        meta = Meta(
            title=get_site_title(title)
        )

        context['is_result_page'] = 'active'
        context['meta'] = meta

        context['student'] = get_current_student(self.request)
        context['semester_grade'] = self.semester_grade[:1].get()
        context['cgpa'] = self.cgpa
        return context

    def get_queryset(self):
        student = get_current_student(self.request)

        try:
            term = Term.objects.filter(pk=self.kwargs['pk'])[:1].get()
        except Term.DoesNotExist:
            term = None

        queryset = super(SelectedTerm, self).get_queryset()
        queryset = queryset.filter(course_enrollment__student=student, course_enrollment__course_offered__term=term)

        self.semester_grade = self.semester_grade.filter(student=student, term=term)
        self.cgpa = student.get_cgpa(self.semester_grade[:1].get())

        return queryset

templates/result/letter_grade.html
{% if grade.letter_grade == 4.00 %}
A
{% elif grade.letter_grade == 3.67 %}
A-
{% elif grade.letter_grade == 3.33 %}
B+
{% elif grade.letter_grade == 3.00 %}
B
{% elif grade.letter_grade == 2.67 %}
B-
{% elif grade.letter_grade == 2.33 %}
C+
{% elif grade.letter_grade == 2.00 %}
C
{% elif grade.letter_grade == 1.67 %}
D
{% elif grade.letter_grade == 0.00 %}
F
{% else %}
-
{% endif %}

templates/result/result_detail.html
{% extends "base.html" %}
{% load mathfilters %}
{% load saiki_extras %}

{% block content %}
{% url 'result:select_term' as my_grades_url %}
{% include '../includes/header.html' with heading=grades.first.course_enrollment.course_offered.term|addstr:" | "|addstr:student.program.university.name btn1_url=my_grades_url btn1_title='Select term' %}

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card bg-default">
                <div class="card-header bg-transparent border-0">
                    <h3 class="text-white mb-0">
                        Grades - {{grades.first.course_enrollment.course_offered.term}}
                    </h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-dark table-flush">
                        <thead class="thead-dark">
                            <tr>
                                <th class="w-10">Code</th>
                                <th class="w-auto">Course Description</th>
                                <th class="w-10">Unit</th>
                                <th class="w-10">Grade</th>
                                <th class="w-10">Grade Point</th>
                            </tr>
                        </thead>
                        <tbody class="list">
                            {% for grade in grades %}
                                <tr>
                                    <td>{{ grade.course_enrollment.course_offered.course.code }}</td>
                                    <td>{{ grade.course_enrollment.course_offered.course.description }}</td>
                                    <td>{{ grade.course_enrollment.course_offered.course.units }}</td>
                                    <td>{% include './letter_grade.html' %}</td>

                                    {% if grade.letter_grade != None %}
                                        <td>{{ grade.letter_grade|mul:grade.course_enrollment.course_offered.course.units }}</td>
                                    {% else %}
                                        <td>-</td>
                                    {% endif %}

                                </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot class="thead-light">
                            <tr>
                                {% if semester_grades %}
                                    {% for s_grade in semester_grades %}
                                        <th colspan="3"></th>
                                        <th scope="row" colspan="1">SGPA</th>
                                        <th colspan="1">{{ s_grade.semester_gpa }}</th>
                                    {% endfor %}
                                {% elif semester_grade %}
                                    <th colspan="3"></th>
                                    <th scope="row" colspan="1">SGPA</th>
                                    <th colspan="1">{{ semester_grade.semester_gpa }}</th>
                                {% else %}
                                    <th colspan="3"></th>
                                    <th scope="row" colspan="1">SGPA</th>
                                    <th colspan="1">-</th>
                                {% endif %}
                            </tr>
                            <tr>
                                <th colspan="3"></th>
                                <th scope="row" colspan="1">CGPA</th>
                                <th colspan="1">{{ cgpa }}</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/result/result_list.html
{% extends "base.html" %}

{% block content %}
<!-- Header -->
{% url 'result:index' as result_url %}
{% include '../includes/header.html' with heading='My grades' btn1_url=result_url btn1_title='Current results' %}

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card bg-default">
                <div class="card-header bg-transparent border-0">
                    <h3 class="text-white mb-0">
                        Select a Term
                    </h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-dark table-flush">
                        <thead class="thead-dark">
                            <tr>
                                <th class="w-auto">Term</th>
                                <th class="w-10">SGPA</th>
                            </tr>
                        </thead>
                        <tbody class="list">
                            {% for semester_grade in semester_grades %}
                                <tr>
                                    <td>
                                        <a href={% url 'result:by_term' semester_grade.term.pk %} class="name mb-0 text-sm text-white">{{semester_grade.term}}</a>
                                    </td>
                                    <td>{{semester_grade.semester_gpa}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}