resources/api/urls.py
from django.urls import include, path
from .views import ResourceFileList, ResourceFolderDestroy, ResourceFileDestroy, ResourceFolderCreate, ResourceFileCreate

app_name = 'resources'
urlpatterns = [
    path("resources/<str:folder_slug>/", ResourceFileList.as_view(), name="folder_list"),
    path("resources/d/create/", ResourceFolderCreate.as_view(), name="folder_create"),
    path("resources/f/create/", ResourceFileCreate.as_view(), name="file_create"),
    path("resources/d/<int:pk>/", ResourceFolderDestroy.as_view(), name="folder_detail"),
    path("resources/f/<int:pk>/", ResourceFileDestroy.as_view(), name="file_detail"),
]

saiki/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from accounts.views import HomePageView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

api_urlpatterns = [
   url(r'^', include('course.api.urls', namespace='course_api')),
   url(r'^', include('assignment.api.urls', namespace='assignment_api')),
   url(r'^', include('resources.api.urls', namespace='resources_api')),
]

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('api/', include(api_urlpatterns)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('c/', include('course.urls', namespace='course')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts1/', include('allauth.urls')),
    path('announcement/', include('announcement.urls', namespace='announcement')),
    path(r'comments/', include('django_comments_xtd.urls')),
    path(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('r/', include('result.urls', namespace='result')),
    path('w/', include('assignment.urls', namespace='assignment')),
    path('admin/', admin.site.urls),
    path('avatar/', include('avatar.urls')),
    url('^inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

admin.site.site_header = "Saiki Administration"
admin.site.site_title = "Saiki Administration Portal"
admin.site.index_title = "Welcome to Saiki Administration Portal"

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/resources/resource_detail.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load static %}

{% block content %}

{% include '../includes/header_course.html' %}

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div id="resources-app"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_1 %}
<script src="https://unpkg.com/react@17/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js" crossorigin></script>

<script>
window.resources_list_app_props = {
	user: {{ user.pk }},
    is_student: {{ is_student|yesno:"true,false" }},
    is_teacher: {{ is_teacher|yesno:"true,false" }},
	course_offering: {{ course.pk }},
	folder_create_url: "{% url 'resources_api:folder_create' %}",
	file_create_url: "{% url 'resources_api:file_create' %}",
	request_url: "{% url 'resources_api:folder_list' object.slug %}",
};
Object.freeze(window.resources_list_app_props);
</script>

{% render_bundle 'resources' 'js' %}
{% render_bundle 'vendors' 'js' %}

{% endblock %}